INSERT INTO PRODUCTOS (NOMBRE, PRECIO, CREATE_AT) VALUES ('PANASONIC', 800, NOW());
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, CREATE_AT) VALUES ('SONY', 760, NOW());
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, CREATE_AT) VALUES ('APPLE', 1500, NOW());